---
title: 16.有时间限制的Promise对象 - 中等
---
题目：
请你编写一个函数，它接受一个异步函数 `fn` 和一个以毫秒为单位的时间 `t`。它应根据限时函数返回一个有 **限时** 效果的函数。函数 `fn` 接受提供给 **限时** 函数的参数。

**限时** 函数应遵循以下规则：

- 如果 `fn` 在 `t` 毫秒的时间限制内完成，**限时** 函数应返回结果。
- 如果 `fn` 的执行超过时间限制，**限时** 函数应拒绝并返回字符串 `"Time Limit Exceeded"` 。

**示例 1：**

**输入：**
```js
fn = async (n) => { 
  await new Promise(res => setTimeout(res, 100)); 
  return n * n; 
}
inputs = [5]
t = 50
```
**输出：** `{"rejected":"Time Limit Exceeded","time":50}`
**解释：**
```js
const limited = timeLimit(fn, t)
const start = performance.now()
let result;
try {
   const res = await limited(...inputs)
   result = {"resolved": res, "time": Math.floor(performance.now() - start)};
} catch (err) {
   result = {"rejected": err, "time": Math.floor(performance.now() - start)};
}
console.log(result) // 输出结果
```
提供的函数设置在 100ms 后执行完成，但是设置的超时时间为 50ms，所以在 t=50ms 时拒绝因为达到了超时时间。


## 答案

方法 1：在新 Promise 内部调用函数
我们可以创建一个新的 Promise，它在传递的函数解析或拒绝时立即解析。这本质上是模拟了传递的函数，而不对其产生任何影响。要满足要求，我们只需要添加一个 setTimeout，它可以提前强制拒绝 Promise。
```js
var timeLimit = function(fn, t) {
  return async function(...args) {
    return new Promise((resolve, reject) => {
      setTimeout(() => {
        reject("Time Limit Exceeded");
      }, t);
      fn(...args).then(resolve).catch(reject);
    })
  }
};
```
额外的这里的timout可以在`.finally`清除
```js
var timeLimit = function(fn, t) {
    return async function(...args) {
        const promise = new Promise((resolve,reject) =>{
            const timeout = setTimeout(()=>reject("Time Limit Exceeded"),t);
            fn(...args)
                .then(resolve)
                .catch(reject)
                .finally(()=>clearTimeout(timeout))
        })
        return promise
    }
};
```


方法 2：Promise.race
以通过使用 Promise.race 函数来简化代码。它接受一个 Promise 数组并返回一个新的 Promise。返回的 Promise 将解析或拒绝数组中第一个被解析或拒绝的 Promise 的值。

```js
var timeLimit = function(fn, t) {
  return async function(...args) {
    const timeLimitPromise = new Promise((resolve, reject) => {
      setTimeout(() => reject("Time Limit Exceeded"), t)
    });
    const returnedPromise = fn(...args);
    return Promise.race([timeLimitPromise, returnedPromise]);
  }
};
```

方法 3：Async/await
```js
var timeLimit = function(fn,t){
	return async function(...args){
		return new Promise(async (resolve, reject) =>{
			const timeout = setTimeout(() => reject("Time Limit Exceeded"), t)
			try{
				const result = await fn(...args);
				resolve(result)
			}catch(error){
				reject(error)
			}
			clearTimeout(timeout)
		})
	}
}
```
### 解析

这个问题要求你增强一个异步函数，以便它返回的 Promise 会在时间限制到期时自动拒绝。

#### 时间限制的用例

你可能遇到过一些代码会一遍又一遍地重复执行。一个常见的例子是将数据加载到缓存中并使其与数据源保持同步。
```js
async function repeatProcessIndefinitely() {
  while (true) {
    try {
      await someProcess();
    } catch (e) {
      console.error(e);
    }
  }
}
```
如果 someProcess 永远无法完成，循环将被冻结，什么都不会发生。强制 someProcess 抛出错误将取消进程的冻结状态。

需要考虑的重要问题是，即使 Promise 被拒绝，someProcess 中的代码仍然可以继续执行。因此，可能会有多个代码块并行执行。更好的解决方案可能是解决导致冻结的根本问题，或者实施适当的取消。考虑解决“设计可取消的函数”以实现真正的取消。

以下代码展示了要在一小时后强制 Promise someProcess() 被拒绝：

```js
const ONE_HOUR_IN_MS = 3600 * 1000;
const timeLimitedProcess = timeLimit(someProcess, ONE_HOUR_IN_MS);
```

